DELIMITER $
CREATE PROCEDURE Conta_IES_UF()
BEGIN
	SELECT COUNT(CO_IES) AS NUM_IES, SGL_UF AS UF FROM IES, UF WHERE CO_UF_IES = CO_UF GROUP BY CO_UF;
END $
DELIMITER $;


DELIMITER $$
CREATE PROCEDURE Conta_Sexo()
BEGIN
	SELECT COUNT(CO_DOCENTE) AS NUM_DOCENTES, DS_SEXO AS SEXO FROM DOCENTE INNER JOIN SEXO GROUP BY SEXO;
END $$
DELIMITER $$;

