DELIMITER $
CREATE PROCEDURE Conta_Docentes_Por_IES()
BEGIN
  SELECT COUNT(DOCENTE.CO_DOCENTE) AS TOTAL_DOCENTES, NO_IES FROM DOCENTE, IES_DOCENTE, IES WHERE DOCENTE.CO_DOCENTE = IES_DOCENTE.CO_DOCENTE AND IES_DOCENTE.CO_IES = IES.CO_IES GROUP BY IES_DOCENTE.CO_IES;
END $
DELIMITER $;