-- -----------------------------------------------------
-- Tabela MANTENEDORA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS MANTENEDORA (
  CO_MANTENEDORA INT NOT NULL,
  NO_MANTENEDORA VARCHAR(45),
  PRIMARY KEY (CO_MANTENEDORA)
)

-- -----------------------------------------------------
-- Tabela CATEGORIA_ADMINISTRATIVA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CATEGORIA_ADMINISTRATIVA (
  CO_CATEGORIA_ADMINISTRATIVA INT NOT NULL,
  DS_CATEGORIA_ADMINISTRATIVA VARCHAR(45),
  PRIMARY KEY (CO_CATEGORIA_ADMINISTRATIVA)
)

-- -----------------------------------------------------
-- Tabela ORGANIZACAO_ACADEMICA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ORGANIZACAO_ACADEMICA (
  CO_ORGANIZACAO_ACADEMICA INT NOT NULL,
  DS_ORGANIZACAO_ACADEMICA VARCHAR(45),
  PRIMARY KEY (CO_ORGANIZACAO_ACADEMICA)
)

-- -----------------------------------------------------
-- Tabela UF
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS UF (
  CO_UF INT NOT NULL,
  SGL_UF VARCHAR(15),
  PRIMARY KEY (CO_UF)
)

-- -----------------------------------------------------
-- Tabela MUNICIPIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS MUNICIPIO (
  CO_MUNICIPIO INT NOT NULL,
  NO_MUNICIPIO VARCHAR(45),
  PRIMARY KEY (CO_MUNICIPIO)
)



-- -----------------------------------------------------
-- Tabela IES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS IES (
  CO_IES INT NOT NULL,
  NO_IES VARCHAR(45) NOT NULL,
  SGL_IES VARCHAR(45) NULL,
  CO_MUNICIPIO_IES INT NULL,
  CO_UF_IES INT NULL,
  NO_REGIAO_IES VARCHAR(45) NULL,
  IN_CAPITAL_IES INT NULL,
  IN_ACESSO_PORTAL_CAPES INT NULL,
  IN_ACESSO_OUTRAS_BASES INT NULL,
  IN_REPOSITORIO_INSTITUCIONAL INT NULL,
  IN_BUSCA_INTEGRADA INT NULL,
  IN_SERVICO_INTERNET INT NULL,
  IN_PARTICIPA_REDE_SOCIAL INT NULL,
  IN_CATALOGO_ONLINE INT NULL,
  QT_PERIODICO_ELETRONICO INT NULL,
  QT_LIVRO_ELETRONICO INT NULL,
  CO_MANTENEDORA INT NOT NULL,
  CO_CATEGORIA_ADMINISTRATIVA INT NOT NULL,
  CO_ORGANIZACAO_ACADEMICA INT NOT NULL,
  PRIMARY KEY (CO_IES),
    FOREIGN KEY (CO_MANTENEDORA) REFERENCES MANTENEDORA (CO_MANTENEDORA),
    FOREIGN KEY (CO_CATEGORIA_ADMINISTRATIVA) REFERENCES CATEGORIA_ADMINISTRATIVA (CO_CATEGORIA_ADMINISTRATIVA),
    FOREIGN KEY (CO_ORGANIZACAO_ACADEMICA) REFERENCES ORGANIZACAO_ACADEMICA (CO_ORGANIZACAO_ACADEMICA),
    FOREIGN KEY (CO_UF_IES) REFERENCES UF (CO_UF),
    FOREIGN KEY (CO_MUNICIPIO_IES) REFERENCES MUNICIPIO (CO_MUNICIPIO)
)


-- -----------------------------------------------------
-- Tabela COR_RACA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS COR_RACA (
  CO_COR_RACA INT NOT NULL,
  DS_COR_RACA VARCHAR(45),
  PRIMARY KEY (CO_COR_RACA)
)

-- -----------------------------------------------------
-- Tabela SEXO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS SEXO (
  IN_SEXO INT NOT NULL,
  DS_SEXO VARCHAR(45),
  PRIMARY KEY (IN_SEXO)
)


-- -----------------------------------------------------
-- Tabela ALUNO_SITUACAO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ALUNO_SITUACAO (
  CO_ALUNO_SITUACAO INT NOT NULL,
  DS_ALUNO_SITUACAO VARCHAR(45),
  PRIMARY KEY (CO_ALUNO_SITUACAO)
)

-- -----------------------------------------------------
-- Tabela NACIONALIDADE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS NACIONALIDADE (
  CO_NACIONALIDADE INT NOT NULL,
  DS_NACIONALIDADE VARCHAR(45),
  PRIMARY KEY (CO_NACIONALIDADE)
)

-- -----------------------------------------------------
-- Tabela TURNO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TURNO (
  CO_TURNO INT NOT NULL,
  DS_TURNO VARCHAR(45) NULL,
  PRIMARY KEY (CO_TURNO)
)

-- -----------------------------------------------------
-- Tabela ALUNO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ALUNO (
  CO_ALUNO INT NOT NULL,
  NU_ANO_ALUNO_NASC INT,
  NU_MES_ALUNO_NASC INT NULL,
  NU_DIA_ALUNO_NASC INT NULL,
  NU_IDADE_ALUNO INT NULL,
  CO_PAIS_ORIGEM_ALUNO INT NULL,
  IN_ALUNO_DEF_TGD_SUPER INT NULL,
  IN_DEF_AUDITIVA INT NULL,
  IN_DEF_FISICA INT NULL,
  IN_DEF_INTELECTUAL INT NULL,
  IN_DEF_MULTIPLA INT NULL,
  IN_DEF_SURDEZ INT NULL,
  IN_DEF_SURDOCEGUEIRA INT NULL,
  IN_DEF_BAIXA_VISAO INT NULL,
  IN_DEF_CEGUEIRA INT NULL,
  IN_DEF_SUPERDOTACAO INT NULL,
  IN_TGD_AUTISMO_INFANTIL INT NULL,
  IN_TGD_SINDROME_ASPERGER INT NULL,
  IN_TGD_SINDROME_RETT INT NULL,
  IN_TGD_TRANSTOR_DESINTEGRATIVO INT NULL,
  QT_CARGA_HORARIA_TOTAL INT NULL,
  QT_CARGA_HORARIA_INTEG INT NULL,
  DT_INGRESSO_CURSO DATE NULL,
  IN_ING_VESTIBULAR INT NULL,
  IN_ING_ENEM INT NULL,
  IN_ING_AVALIACAO_SERIADA INT NULL,
  IN_ING_SELECAO_SIMPLIFICADA INT NULL,
  IN_ING_SELECAO_VAGA_REMANESC INT NULL,
  IN_ING_SELECAO_VAGA_PROG_ESPEC INT NULL,
  IN_ING_TRANSF_EXOFFICIO INT NULL,
  IN_ING_DECISAO_JUDICIAL INT NULL,
  IN_ING_CONVENIO_PECG INT NULL,
  IN_RESERVA_VAGAS INT NULL,
  IN_RESERVA_ETNICO INT NULL,
  IN_RESERVA_DEFICIENCIA INT NULL,
  IN_RESERVA_ENSINO_PUBLICO INT NULL,
  IN_RESERVA_RENDA_FAMILIAR INT NULL,
  IN_RESERVA_OUTRA INT NULL,
  IN_FINANC_ESTUDANTIL INT NULL,
  IN_FIN_REEMB_FIES INT NULL,
  IN_FIN_REEMB_ESTADUAL INT NULL,
  IN_FIN_REEMB_MUNICIPAL INT NULL,
  IN_FIN_REEMB_PROG_IES INT NULL,
  IN_FIN_REEMB_ENT_EXTERNA INT NULL,
  IN_FIN_REEMB_OUTRA INT NULL,
  IN_FIN_NAOREEMB_PROUNI_INTEGR INT NULL,
  IN_FIN_NAOREEMB_PROUNI_PARCIAL INT NULL,
  IN_FIN_NAOREEMB_ESTADUAL INT NULL,
  IN_FIN_NAOREEMB_MUNICIPAL INT NULL,
  IN_FIN_NAOREEMB_PROG_IES INT NULL,
  IN_FIN_NAOREEMB_ENT_EXTERNA INT NULL,
  IN_FIN_NAOREEMB_OUTRA INT NULL,
  IN_APOIO_SOCIAL INT NULL,
  IN_APOIO_ALIMENTACAO INT NULL,
  IN_APOIO_BOLSA_PERMANENCIA INT NULL,
  IN_APOIO_BOLSA_TRABALHO INT NULL,
  IN_APOIO_MATERIAL_DIDATICO INT NULL,
  IN_APOIO_MORADIA INT NULL,
  IN_APOIO_TRANSPORTE INT NULL,
  IN_ATIVIDADE_EXTRACURRICULAR INT NULL,
  IN_COMPL_ESTAGIO INT NULL,
  IN_COMPL_EXTENSAO INT NULL,
  IN_COMPL_MONITORIA INT NULL,
  IN_COMPL_PESQUISA INT NULL,
  IN_BOLSA_ESTAGIO INT NULL,
  IN_BOLSA_EXTENSAO INT NULL,
  IN_BOLSA_MONITORIA INT NULL,
  IN_BOLSA_PESQUISA INT NULL,
  CO_TIPO_ESCOLA_ENS_MEDIO INT NULL,
  IN_ALUNO_PARFOR INT NULL,
  CO_SEMESTRE_CONCLUSAO INT NULL,
  CO_SEMESTRE_REFERENCIA INT NULL,
  IN_MOBILIDADE_ACADEMICA INT NULL,
  CO_MOBILIDADE_ACADEMICA INT NULL,
  CO_MOBILIDADE_ACADEMICA_INTERN INT NULL,
  CO_IES_DESTINO INT NULL,
  CO_PAIS_DESTINO INT NULL,
  IN_MATRICULA INT NULL,
  IN_CONCLUINTE INT NULL,
  IN_INGRESSO_TOTAL INT NULL,
  IN_INGRESSO_VAGA_NOVA INT NULL,
  ANO_INGRESSO INT NULL,
  CO_IES INT NOT NULL,
  CO_COR_RACA_ALUNO INT NOT NULL,
  IN_SEXO_ALUNO INT NOT NULL,
  CO_ALUNO_SITUACAO INT NOT NULL,
  CO_NACIONALIDADE_ALUNO INT NOT NULL,
  CO_UF_NASCIMENTO INT NOT NULL,
  CO_MUNICIPIO_NASCIMENTO INT NOT NULL,
  CO_TURNO_ALUNO INT NOT NULL,
  PRIMARY KEY (CO_ALUNO),
    FOREIGN KEY (CO_IES) REFERENCES IES (CO_IES),
    FOREIGN KEY (CO_COR_RACA_ALUNO) REFERENCES COR_RACA (CO_COR_RACA),
    FOREIGN KEY (IN_SEXO_ALUNO) REFERENCES SEXO (IN_SEXO),
    FOREIGN KEY (CO_ALUNO_SITUACAO) REFERENCES ALUNO_SITUACAO (CO_ALUNO_SITUACAO),
    FOREIGN KEY (CO_NACIONALIDADE_ALUNO) REFERENCES NACIONALIDADE (CO_NACIONALIDADE),
    FOREIGN KEY (CO_UF_NASCIMENTO) REFERENCES UF (CO_UF),
    FOREIGN KEY (CO_MUNICIPIO_NASCIMENTO) REFERENCES MUNICIPIO (CO_MUNICIPIO),
    FOREIGN KEY (CO_TURNO_ALUNO) REFERENCES TURNO (CO_TURNO)
)


-- -----------------------------------------------------
-- Tabela TECNICO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TECNICO (
  CO_IES INT NOT NULL,
  QT_TEC_TOTAL INT NULL,
  QT_TEC_FUND_INCOMP_FEM INT NULL,
  QT_TEC_FUND_INCOMP_MASC INT NULL,
  QT_TEC_FUND_COMP_FEM INT NULL,
  QT_TEC_FUND_COMP_MASC INT NULL,
  QT_TEC_MEDIO_FEM INT NULL,
  QT_TEC_MEDIO_MASC INT NULL,
  QT_TEC_SUPERIOR_FEM INT NULL,
  QT_TEC_SUPERIOR_MASC INT NULL,
  QT_TEC_ESPECIALIZACAO_FEM INT NULL,
  QT_TEC_ESPECIALIZACAO_MASC INT NULL,
  QT_TEC_MESTRADO_FEM INT NULL,
  QT_TEC_MESTRADO_MASC INT NULL,
  QT_TEC_DOUTORADO_FEM INT NULL,
  QT_TEC_DOUTORADO_MASC INT NULL,
  PRIMARY KEY (CO_IES),
    FOREIGN KEY (CO_IES) REFERENCES IES (CO_IES)
)
-- -----------------------------------------------------
-- Tabela VALORES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS VALORES (
  CO_IES INT NOT NULL,
  VL_RECEITA_PROPRIA FLOAT NULL,
  VL_TRANSFERENCIA FLOAT NULL,
  VL_OUTRA_RECEITA FLOAT NULL,
  VL_DES_PESSOAL_REM_DOCENTE FLOAT NULL,
  VL_DES_PESSOAL_REM_TECNICO FLOAT NULL,
  VL_DES_PESSOAL_ENCARGO FLOAT NULL,
  VL_DES_CUSTEIO FLOAT NULL,
  VL_DES_INVESTIMENTO FLOAT NULL,
  VL_DES_PESQUISA FLOAT NULL,
  VL_DES_OUTRAS FLOAT NULL,
  PRIMARY KEY (CO_IES),
    FOREIGN KEY (CO_IES) REFERENCES IES (CO_IES)
)


-- -----------------------------------------------------
-- Tabela LOCAL_OFERTA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS LOCAL_OFERTA (
  CO_LOCAL_OFERTA INT NOT NULL,
  NO_LOCAL_OFERTA VARCHAR(45) NULL,
  CO_UF_LOCAL_OFERTA INT NULL,
  CO_MUNICIPIO_LOCAL_OFERTA INT NULL,
  IN_SEDE INT NULL,
  CO_CURSO_POLO INT NULL,
  IN_LOCAL_OFERTA_NEAD INT NULL,
  IN_LOCAL_OFERTA_UAB INT NULL,
  IN_LOCAL_OFERTA_REITORIA INT NULL,
  IN_LOCAL_OFERTA_POLO INT NULL,
  IN_LOCAL_OFERTA_UNID_ACADEMICA INT NULL,
  DT_INICIO_FUNCIONAMENTO DATE NULL,
  IES_CO_IES INT NOT NULL,
  PRIMARY KEY (CO_LOCAL_OFERTA),
    FOREIGN KEY (IES_CO_IES) REFERENCES IES (CO_IES),
    FOREIGN KEY (CO_UF_LOCAL_OFERTA) REFERENCES UF (CO_UF),
    FOREIGN KEY (CO_MUNICIPIO_LOCAL_OFERTA) REFERENCES MUNICIPIO (CO_MUNICIPIO)
)


-- -----------------------------------------------------
-- Tabela CURSO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CURSO (
  CO_MUNICIPIO_CURSO INT NULL,
  CO_UF_CURSO INT NULL,
  NO_REGIAO_CURSO VARCHAR(45) NULL,
  IN_CAPITAL_CURSO INT NULL,
  CO_CURSO INT NOT NULL,
  NO_CURSO VARCHAR(45) NULL,
  CO_SITUACAO_CURSO INT NULL,
  DS_SITUACAO_CURSO VARCHAR(45) NULL,
  CO_OCDE INT NULL,
  NO_OCDE VARCHAR(45) NULL,
  CO_OCDE_AREA_GERAL INT NULL,
  NO_OCDE_AREA_GERAL VARCHAR(45) NULL,
  CO_OCDE_AREA_ESPECIFICA INT NULL,
  NO_OCDE_AREA_ESPECIFICA VARCHAR(45) NULL,
  CO_OCDE_AREA_DETALHADA INT NULL,
  NO_OCDE_AREA_DETALHADA VARCHAR(45) NULL,
  CO_GRAU_ACADEMICO INT NULL,
  DS_GRAU_ACADEMICO VARCHAR(45) NULL,
  CO_MODALAIDADE_ENSINO INT NULL,
  DS_MODALIDADE_ENSINO VARCHAR(45) NULL,
  CO_NIVEL_ACADEMICO INT NULL,
  DS_NIVEL_ACADEMICO VARCHAR(45) NULL,
  IN_GRATUITO INT NULL,
  TP_ATRIBUTO_INGRESSO INT NULL,
  NU_CARGA_HORARIA INT NULL,
  DT_INICIO_FUNCIONAMENTO DATE NULL,
  DT_AUTORIZACAO_CURSO DATE NULL,
  IN_AJUDA_DEFICIENTE INT NULL,
  IN_MATERIAL_DIGITAL INT NULL,
  IN_MATERIAL_AMPLIADO INT NULL,
  IN_MATERIAL_TATIL INT NULL,
  IN_MATERIAL_IMPRESSO INT NULL,
  IN_MATERIAL_AUDIO INT NULL,
  IN_MATERIAL_BRAILLE INT NULL,
  IN_MATERIAL_LIBRAS INT NULL,
  IN_DISCIPLINA_LIBRAS INT NULL,
  IN_TRADUTOR_LIBRAS INT NULL,
  IN_GUIA_INTERPRETE INT NULL,
  IN_RECURSOS_COMUNICACAO INT NULL,
  IN_RECURSOS_INFORMATICA INT NULL,
  IN_INTEGRAL_CURSO INT NULL,
  IN_MATUTINO_CURSO INT NULL,
  IN_VESPERTINO_CURSO INT NULL,
  IN_NOTURNO_CURSO INT NULL,
  NU_INTEGRALIZACAO_INTEGRAL FLOAT NULL,
  NU_INTEGRALIZACAO_MATUTINO FLOAT NULL,
  NU_INTEGRALIZACAO_VESPERTINO FLOAT NULL,
  NU_INTEGRALIZACAO_NOTURNO FLOAT NULL,
  NU_INTEGRALIZACAO_EAD FLOAT NULL,
  IN_OFERECE_DISC_SEMI_PRES INT NULL,
  NU_PERC_CAR_HOR_SEMI_PRES FLOAT NULL,
  IN_POSSUI_LABORATORIO INT NULL,
  QT_INSC_VAGAS_NOVAS_INT INT NULL,
  QT_INSC_VAGAS_NOVAS_MAT INT NULL,
  QT_INSC_VAGAS_NOVAS_VESP INT NULL,
  QT_INSC_VAGAS_NOVAS_NOT INT NULL,
  QT_INSC_VAGAS_NOVAS_EAD INT NULL,
  QT_INSC_VAGAS_REMAN_INT INT NULL,
  QT_INSC_VAGAS_REMAN_MAT INT NULL,
  QT_INSC_VAGAS_REMAN_VESP INT NULL,
  QT_INSC_VAGAS_REMAN_NOT INT NULL,
  QT_INSC_VAGAS_REMAN_EAD INT NULL,
  QT_INSC_VAGAS_PROG_ESP_INT INT NULL,
  QT_INSC_VAGAS_PROG_ESP_MAT INT NULL,
  QT_INSC_VAGAS_PROG_ESP_VESP INT NULL,
  QT_INSC_VAGAS_PROG_ESP_NOT INT NULL,
  QT_INSC_VAGAS_PROG_ESP_EAD INT NULL,
  QT_VAGAS_NOVAS_INTEGRAL INT NULL,
  QT_VAGAS_NOVAS_MATUTINO INT NULL,
  QT_VAGAS_NOVAS_VESPERTINO INT NULL,
  QT_VAGAS_NOVAS_NOTURNO INT NULL,
  QT_VAGAS_NOVAS_EAD INT NULL,
  QT_VAGAS_REMANESC_INTEGRAL INT NULL,
  QT_VAGAS_REMANESC_MATUTINO INT NULL,
  QT_VAGAS_REMANESC_VESPERTINO INT NULL,
  QT_VAGAS_REMANESC_NOTURNO INT NULL,
  QT_VAGAS_REMANESC_EAD INT NULL,
  QT_VAGAS_PROG_ESP_INTEGRAL INT NULL,
  QT_VAGAS_PROG_ESP_MATUTINO INT NULL,
  QT_VAGAS_PROG_ESP_VESPERTINO INT NULL,
  QT_VAGAS_PROG_ESP_NOTURNO INT NULL,
  QT_VAGAS_PROG_ESP_EAD INT NULL,
  QT_MATRICULA_CURSO INT NULL,
  QT_CONCLUINTE_CURSO INT NULL,
  QT_INGRESSO_CURSO INT NULL,
  QT_INGRESSO_VAGAS_NOVAS INT NULL,
  QT_VAGAS_TOTAIS INT NULL,
  CO_IES INT NOT NULL,
  CO_LOCAL_OFERTA INT NOT NULL,
  PRIMARY KEY (CO_CURSO),
    FOREIGN KEY (CO_IES) REFERENCES IES (CO_IES),
    FOREIGN KEY (CO_LOCAL_OFERTA) REFERENCES LOCAL_OFERTA (CO_LOCAL_OFERTA),
    FOREIGN KEY (CO_UF_CURSO) REFERENCES UF (CO_UF),
    FOREIGN KEY (CO_MUNICIPIO_CURSO) REFERENCES MUNICIPIO (CO_MUNICIPIO)
)


-- -----------------------------------------------------
-- Tabela CURSO_ALUNO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CURSO_ALUNO (
  CURSO_CO_CURSO INT NOT NULL,
  CO_ALUNO INT NOT NULL,
  CO_ALUNO_CURSO INT NULL,
  CO_ALUNO_CURSO_ORIGEM INT NULL,
  PRIMARY KEY (CURSO_CO_CURSO, CO_ALUNO), 
    FOREIGN KEY (CURSO_CO_CURSO) REFERENCES CURSO (CO_CURSO),
    FOREIGN KEY (CO_ALUNO) REFERENCES ALUNO (CO_ALUNO)
)

-- -----------------------------------------------------
-- Tabela SITUACAO_DOCENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS SITUACAO_DOCENTE (
  CO_SITUACAO_DOCENTE INT NOT NULL,
  DS_SITUACAO_DOCENTE VARCHAR(45) NULL,
  PRIMARY KEY (CO_SITUACAO_DOCENTE)
)

-- -----------------------------------------------------
-- Tabela ESCOLARIDADE_DOCENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ESCOLARIDADE_DOCENTE (
  CO_ESCOLARIDADE_DOCENTE INT NOT NULL,
  DS_ESCOLARIDADE_DOCENTE VARCHAR(45) NULL,
  PRIMARY KEY (CO_ESCOLARIDADE_DOCENTE)
)

-- -----------------------------------------------------
-- Tabela REGIME_TRABALHO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS REGIME_TRABALHO (
  CO_REGIME_TRABALHO INT NOT NULL,
  DS_REGIME_TRABALHO VARCHAR(45) NULL,
  PRIMARY KEY (CO_REGIME_TRABALHO),
)

-- -----------------------------------------------------
-- Tabela DOCENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DOCENTE (
  CO_DOCENTE INT NOT NULL,
  NU_ANO_DOCENTE_NASC INT NULL,
  NU_MES_DOCENTE_NASC INT NULL,
  NU_DIA_DOCENTE_NASC INT NULL,
  NU_IDADE_DOCENTE INT NULL,
  CO_PAIS_DOCENTE INT NULL,
  CO_UF_NASCIMENTO INT NULL,
  CO_MUNICIPIO_NASCIMENTO INT NULL,
  IN_DOCENTE_DEFICIENCIA INT NULL,
  IN_DEF_CEGUEIRA INT NULL,
  IN_DEF_BAIXA_VISAO INT NULL,
  IN_DEF_SURDEZ INT NULL,
  IN_DEF_AUDITIVA INT NULL,
  IN_DEF_FISICA INT NULL,
  IN_DEF_SURDOCEGUEIRA INT NULL,
  IN_DEF_MULTIPLA INT NULL,
  IN_DEF_INTELECTUAL INT NULL,
  IN_ATU_EAD INT NULL,
  IN_ATU_EXTENSAO INT NULL,
  IN_ATU_GESTAO INT NULL,
  IN_ATU_GRAD_PRESENCIAL INT NULL,
  IN_ATU_POS_EAD INT NULL,
  IN_ATU_POS_PRESENCIAL INT NULL,
  IN_ATU_SEQUENCIAL INT NULL,
  IN_ATU_PESQUISA INT NULL,
  IN_BOLSA_PESQUISA INT NULL,
  IN_SUBSTITUTO INT NULL,
  IN_EXERCICIO_DT_REF INT NULL,
  IN_VISITANTE INT NULL,
  IN_VISITANTE_IFES_VINCULO INT NULL,
  CO_SITUACAO_DOCENTE INT NOT NULL,
  CO_SEXO_DOCENTE INT NOT NULL,
  CO_NACIONALIDADE_DOCENTE INT NOT NULL,
  CO_COR_RACA_DOCENTE INT NOT NULL,
  CO_UF_NASCIMENTO INT NOT NULL,
  CO_MUNICIPIO_NASCIMENTO INT NOT NULL,
  CO_ESCOLARIDADE_DOCENTE INT NOT NULL,
  CO_REGIME_TRABALHO INT NOT NULL,
  PRIMARY KEY (CO_DOCENTE),
    FOREIGN KEY (CO_SITUACAO_DOCENTE) REFERENCES SITUACAO_DOCENTE (CO_SITUACAO_DOCENTE),
    FOREIGN KEY (CO_SEXO_DOCENTE) REFERENCES SEXO (IN_SEXO),
    FOREIGN KEY (CO_NACIONALIDADE_DOCENTE) REFERENCES NACIONALIDADE (CO_NACIONALIDADE),
    FOREIGN KEY (CO_COR_RACA_DOCENTE) REFERENCES COR_RACA (CO_COR_RACA),
    FOREIGN KEY (CO_UF_NASCIMENTO) REFERENCES UF (CO_UF),
    FOREIGN KEY (CO_MUNICIPIO_NASCIMENTO) REFERENCES MUNICIPIO (CO_MUNICIPIO),
    FOREIGN KEY (CO_ESCOLARIDADE_DOCENTE)REFERENCES ESCOLARIDADE_DOCENTE (CO_ESCOLARIDADE_DOCENTE),
    FOREIGN KEY (CO_REGIME_TRABALHO) REFERENCES REGIME_TRABALHO (CO_REGIME_TRABALHO)
)

-- -----------------------------------------------------
-- Table IES_DOCENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS IES_DOCENTE (
  CO_IES INT NOT NULL,
  CO_DOCENTE INT NOT NULL,
  CO_DOCENTE_IES INT NULL,
  PRIMARY KEY (CO_IES, CO_DOCENTE),
    FOREIGN KEY (CO_IES) REFERENCES IES (CO_IES)
    FOREIGN KEY (CO_DOCENTE) REFERENCES DOCENTE (CO_DOCENTE)
)
