DELIMITER $$
CREATE PROCEDURE Conta_Docentes()
BEGIN
  SELECT 'Numero de docentes: ', COUNT(CO_DOCENTE) FROM DOCENTE;
END $$
DELIMITER $$;

CREATE VIEW MEDIA_TECNICOS AS SELECT AVG(TEC) FROM (SELECT I.NO_IES,T.QT_TEC_TOTAL AS TEC FROM TECNICO AS T INNER JOIN IES AS I ON T.CO_IES=I.CO_IES)TEC_M;

DELIMITER $
CREATE TRIGGER Trig
BEFORE INSERT ON SEXO
FOR EACH ROW
	BEGIN
	IF (NEW.IN_SEXO != 0 AND NEW.IN_SEXO != 1) 
	THEN
  		SET NEW.IN_SEXO = NULL;
	END IF;
END $
DELIMITER $;
