CREATE VIEW View1
AS SELECT AVG(QT_TEC_TOTAL) FROM (SELECT IES.NO_IES,TECNICO.QT_TEC_TOTAL FROM IES,TECNICO WHERE IES.CO_IES=TECNICO.CO_IES);

CREATE TRIGGER Trigger1
BEFORE INSERT ON DOCENTE 
FOR EACH ROW BEGIN
IF NEW.CO_SEXO_DOCENTE != 1 AND NEW.CO_SEXO_DOCENTE != 2 THEN
  SET NEW.CO_SEXO_DOCENTE = NULL;
END IF;
END; 

DELIMITER $$
CREATE PROCEDURE Conta_Docentes()
BEGIN
  SELECT 'Numero de docentes: ', COUNT(CO_DOCENTE) FROM DOCENTE;
END $$
DELIMITER;